### ISSUE TITLE
.DS_Storeをignore

### ISSUE THREAD

**Issue by hakiai** [Turu0512/react-todo-garage#5]
.DS_StoreはMac独自のファイルで、他のメンバーと共有すべきファイルではないので、gitignoreしてください。
.DS_Storeについては基本的にignoreするのが慣習なので、ホームディレクトリ直下の.gitignoreファイルで指定してしまっていいかと思います。
node_modules/も同様です。ignoreへの追加お願いします。

**Comment by hakiai** [comment]
一度commitされたファイルは.gitignoreに追加しても無視されないので、```$ git rm -f .DS_Store```も併せて実行してください

**Comment by Turu0512** [comment]
削除と同時に
defaults write com.apple.desktopservices DSDontWriteNetworkStores True
を実行して作らせないように設定しました。

**Comment by hakiai** [comment]
作らないようにとかできるんですね笑

ただ、これは他のMacユーザーが.DS_Storeを作成した場合、やはりgitに乗ってしまうので、プロジェクトルートに.gitignoreファイルを作成して、ignoreしておく方が親切かと思います。
.DS_Storeとnode_modulesを.gitignoreに追加して、gitの管理に乗らないよう処理お願いします。

**Comment by Turu0512** [comment]
コピペしただけなのでできているのか自信はないです（汗

上記二つのファイルの削除、.gitignoreへの追加完了しました。
表記の仕方あっていますか？

**Comment by hakiai** [comment]
@Turu0512 
はい、あっています！

。。が、ソースコードに変更を加える場合はmainで直接変更せず、必ず別ブランチをpushしてGitHub上でマージするようにしてください！

**Comment by Turu0512** [comment]
あ、、、
申し訳ありません！
気をつけます。
